name: Docker Build and Python Tests

on:
  push:
    branches:
      - Andres2
  pull_request:
    branches:
      - Andres2

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Step 4: Build Docker Images (solo si los tests y la cobertura pasaron)
      - name: Build Docker images
        run: docker-compose build
        if: success()

      # Step 5: Tag and Push Docker Image to GitHub Container Registry
      - name: Tag and Push Docker Image to GitHub Container Registry
        run: |
          docker tag backend ghcr.io/${{ github.repository }}/backend:latest
          docker push ghcr.io/${{ github.repository }}/backend:latest
        if: success()

      # Step 6: Run Python Tests with Coverage
      - name: Run Python Tests with Coverage
        run: |
          docker-compose up -d
          sleep 10 # Esperar a que los servicios estén listos
          docker-compose exec backend pytest --cov=src --cov-fail-under=85 --maxfail=1 --disable-warnings

       # Step 7: Upload test artifacts (Usar upload-artifact v3)
      - name: Upload test artifacts
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: ./test-results/  # Reemplaza con la ruta de tus resultados de prueba
